import React, { useId } from "react";
import { LogoMark } from "@/components/Logo";

const NAV_ITEMS = [
  ["overview", "Aperçu"], ["accounts", "Comptes"], ["journal", "Journal"],
  ["markets", "Marchés"], ["backtest", "Simulateur"], ["analytics", "Statistiques"],
  ["coach", "Analyse IA"], ["discipline", "Discipline"], ["payouts", "Payouts"],
  ["settings", "Paramètres"],
];

const TITLES = { overview:"Aperçu", accounts:"Comptes", journal:"Journal", markets:"Marchés", backtest:"Simulateur", analytics:"Statistiques", coach:"Analyse IA", discipline:"Discipline", payouts:"Payouts" };

const Kpi = ({ label, value, detail, color = "#fff" }) => <div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-2.5"><div className="text-[7px] leading-none text-[#737B8D]">{label}</div><div className="mt-1.5 font-numeric text-[12px] font-bold leading-none" style={{color}}>{value}</div><div className="mt-1 text-[6px] text-[#626A7A]">{detail}</div></div>;

const EquityChart = ({ accent, gradientId }) => <div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-2.5"><div className="flex items-center justify-between text-[7px]"><span className="font-medium text-[#D9DCE5]">Courbe d’équité</span><span className="text-[#626A7A]">30 jours</span></div><svg viewBox="0 0 320 98" className="mt-1 h-[66px] w-full" aria-hidden="true"><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={accent} stopOpacity=".48"/><stop offset="100%" stopColor={accent} stopOpacity="0"/></linearGradient></defs><path d="M0 85 C28 82 38 68 66 72 S102 54 128 59 S164 40 191 45 S228 27 257 31 S292 14 320 9 L320 98 L0 98Z" fill={`url(#${gradientId})`}/><path d="M0 85 C28 82 38 68 66 72 S102 54 128 59 S164 40 191 45 S228 27 257 31 S292 14 320 9" fill="none" stroke={accent} strokeWidth="2"/></svg><div className="flex justify-between text-[5.5px] text-[#4F5665]"><span>10 mai</span><span>17 mai</span><span>24 mai</span><span>31 mai</span><span>7 juin</span></div></div>;

const TradeList = () => <div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-2.5"><div className="mb-1.5 text-[7px] font-medium text-[#D9DCE5]">Trades récents</div>{[["EURUSD","Achat","+1,32 R","#00E676"],["NAS100","Vente","-0,45 R","#FF5252"],["XAUUSD","Achat","+2,11 R","#00E676"],["GBPUSD","Achat","+1,05 R","#00E676"]].map(([instrument,direction,result,color])=><div key={instrument} className="grid grid-cols-[1fr_.8fr_.7fr] border-t border-white/[0.04] py-1 text-[6px]"><span className="font-medium text-[#BFC4D0]">{instrument}</span><span className="text-[#666F80]">{direction}</span><span className="text-right font-numeric" style={{color}}>{result}</span></div>)}</div>;

const InsightCard = ({ accent }) => <div className="rounded-[10px] border border-[#7C4DFF]/20 bg-gradient-to-br from-[#7C4DFF]/15 to-[#4F8CFF]/[0.06] p-2.5"><div className="text-[7px] font-semibold" style={{color:accent}}>✦ Insight Atlas</div><p className="mt-2 text-[6.5px] leading-[1.45] text-[#ADB3C1]">Ton plan est respecté sur 87 % des trades. Garde la même discipline pendant les sessions volatiles.</p><div className="mt-2 text-[6px] font-medium" style={{color:accent}}>Voir l’analyse →</div></div>;

const OverviewPanel = ({ accent, gradientId }) => <><div className="grid grid-cols-4 gap-1.5"><Kpi label="Profit net" value="+12 450 $" detail="30 derniers jours" color="#00E676"/><Kpi label="Score de discipline" value="94/100" detail="Excellent" color={accent}/><Kpi label="Comptes actifs" value="5" detail="Tous suivis" color="#4F8CFF"/><Kpi label="Drawdown restant" value="8 240 $" detail="Marge disponible" color="#FF5252"/></div><div className="mt-1.5 grid grid-cols-[1.8fr_.8fr] gap-1.5"><EquityChart accent={accent} gradientId={gradientId}/><div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-2.5"><div className="text-[7px] font-medium text-[#D9DCE5]">Progression des payouts</div><div className="mt-2 text-[6px] text-[#626A7A]">Topstep · Principal</div><div className="mt-1 text-[11px] font-bold font-numeric">6 240 $ <span className="text-[6px] font-normal text-[#626A7A]">/ 10 000 $</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full w-[62%] rounded-full bg-gradient-to-r from-[#7C4DFF] to-[#4F8CFF]"/></div><div className="mt-1 text-right text-[6px] text-[#8B93A3]">62 %</div></div></div><div className="mt-1.5 grid grid-cols-[1.3fr_.9fr] gap-1.5"><TradeList/><InsightCard accent={accent}/></div></>;

const JournalPanel = ({ accent }) => <><div className="grid grid-cols-4 gap-1.5"><Kpi label="Trades" value="48" detail="30 derniers jours" color="#4F8CFF"/><Kpi label="Win rate" value="62 %" detail="+8 %" color="#00E676"/><Kpi label="Profit net" value="+4 860 $" detail="Toutes stratégies" color="#00E676"/><Kpi label="R moyen" value="1,84 R" detail="Plan respecté" color={accent}/></div><div className="mt-1.5 rounded-[10px] border border-white/[0.065] bg-[#090B13] p-2.5"><div className="flex items-center justify-between"><div className="text-[7px] font-medium">Journal de trading</div><div className="rounded-md border border-white/[0.07] px-2 py-1 text-[5.5px] text-[#8B93A3]">Tous les comptes</div></div><div className="mt-2 grid grid-cols-[1fr_.7fr_.7fr_.7fr] text-[5.5px] uppercase tracking-wide text-[#596170]"><span>Actif</span><span>Session</span><span>Setup</span><span className="text-right">Résultat</span></div>{[["EURUSD","Londres","FVG","+1,32 R"],["NAS100","New York","Breakout","-0,45 R"],["XAUUSD","Londres","Retest","+2,11 R"],["GBPUSD","New York","FVG","+1,05 R"]].map((row,i)=><div key={row[0]} className="grid grid-cols-[1fr_.7fr_.7fr_.7fr] border-t border-white/[0.05] py-2 text-[6.5px]"><span className="font-semibold">{row[0]}</span><span className="text-[#818999]">{row[1]}</span><span className="text-[#818999]">{row[2]}</span><span className="text-right font-numeric" style={{color:i===1?"#FF5252":"#00E676"}}>{row[3]}</span></div>)}</div></>;

const DisciplinePanel = ({ accent, gradientId }) => <div className="grid grid-cols-[.8fr_1.4fr] gap-1.5"><div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-3 text-center"><div className="text-[7px] text-[#737B8D]">Score de discipline</div><div className="mt-4 text-[30px] font-bold font-numeric" style={{color:accent}}>94<span className="text-[9px] text-[#737B8D]">/100</span></div><div className="mt-1 text-[7px] text-[#00E676]">Excellent</div><div className="mx-auto mt-4 h-1.5 w-4/5 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full w-[94%] rounded-full" style={{background:accent}}/></div></div><div className="space-y-1.5"><EquityChart accent={accent} gradientId={gradientId}/><div className="grid grid-cols-2 gap-1.5">{[["Respect du plan","87 %"],["Risque maîtrisé","92 %"],["Patience","90 %"],["Limite journalière","96 %"]].map(([label,value])=><div key={label} className="rounded-lg border border-white/[0.055] bg-[#090B13] p-2"><div className="text-[5.5px] text-[#687181]">{label}</div><div className="mt-1 text-[8px] font-bold" style={{color:accent}}>{value}</div></div>)}</div></div></div>;

const CoachPanel = ({ accent }) => <div className="rounded-[10px] border border-[#7C4DFF]/20 bg-[#090B13] p-3"><div className="flex items-center justify-between"><div><div className="text-[8px] font-semibold" style={{color:accent}}>✦ Analyse comportementale Atlas</div><div className="mt-1 text-[6px] text-[#687181]">Analyse fondée sur ton journal</div></div><div className="rounded-lg bg-[#7C4DFF]/20 px-2 py-1 text-[6px]" style={{color:accent}}>Nouvelle analyse</div></div><div className="mt-3 space-y-2">{[["Jours de la semaine","Tu obtiens tes meilleurs résultats le lundi. Le vendredi concentre davantage de trades hors plan."],["Gestion du risque","Tes pertes restent contenues lorsque le risque initial est inférieur à 1 % du compte."],["Action recommandée","Réduis ton exposition après deux pertes et documente le contexte avant toute nouvelle entrée."]].map(([title,text],i)=><div key={title} className="rounded-lg border border-white/[0.055] bg-white/[0.02] p-2.5"><div className="text-[7px] font-semibold" style={{color:i===2?"#00E676":"#D9DCE5"}}>{title}</div><p className="mt-1 text-[6.2px] leading-[1.45] text-[#8B93A3]">{text}</p></div>)}</div></div>;

const BacktestPanel = ({ accent, gradientId }) => <div className="grid grid-cols-[1.4fr_.8fr] gap-1.5"><EquityChart accent="#4F8CFF" gradientId={gradientId}/><div className="space-y-1.5"><Kpi label="Espérance" value="+0,64 R" detail="Par trade" color="#00E676"/><Kpi label="Drawdown max" value="4,8 %" detail="Simulation" color="#FFB855"/><Kpi label="Profit factor" value="1,72" detail="48 trades" color={accent}/></div></div>;

const PayoutPanel = ({ accent }) => <div className="grid grid-cols-[1.35fr_.85fr] gap-1.5"><div className="rounded-[10px] border border-white/[0.065] bg-[#090B13] p-3"><div className="text-[8px] font-semibold">Progression des payouts</div>{[["Topstep · Principal",72,"7 200 $"],["Apex · Évaluation",48,"4 800 $"],["FTMO · Compte 1",84,"8 400 $"]].map(([name,pct,value])=><div key={name} className="mt-3"><div className="flex justify-between text-[6px]"><span className="text-[#9CA3AF]">{name}</span><span className="font-numeric">{value}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-gradient-to-r from-[#7C4DFF] to-[#4F8CFF]" style={{width:`${pct}%`}}/></div></div>)}</div><div className="space-y-1.5"><Kpi label="Total retiré" value="12 400 $" detail="3 payouts" color="#00E676"/><Kpi label="Prochain estimé" value="3 760 $" detail="Dans 18 jours" color={accent}/><Kpi label="Objectif" value="76 %" detail="Progression" color="#4F8CFF"/></div></div>;

export default function ProductDashboardPreview({ activeSection="overview", accent="#B58BFF", tilted=false, className="" }) {
  const uid=useId().replace(/:/g,"");
  const title=TITLES[activeSection]||TITLES.overview;
  const panel=activeSection==="journal"?<JournalPanel accent={accent}/>:activeSection==="discipline"?<DisciplinePanel accent={accent} gradientId={`discipline-${uid}`}/>:activeSection==="coach"?<CoachPanel accent={accent}/>:activeSection==="backtest"?<BacktestPanel accent={accent} gradientId={`backtest-${uid}`}/>:activeSection==="payouts"?<PayoutPanel accent={accent}/>:<OverviewPanel accent={accent} gradientId={`overview-${uid}`}/>;
  return <div className={`relative mx-auto w-full max-w-[720px] ${className}`} style={{perspective:"1800px"}} role="img" aria-label={`Aperçu du produit PipsEvo — ${title}`}><div className="overflow-hidden rounded-[18px] border border-white/[0.1] bg-[#070910] shadow-[0_45px_100px_-34px_rgba(124,77,255,.62)]" style={tilted?{transform:"rotateY(-10deg) rotateX(4deg) rotateZ(-.7deg)",transformStyle:"preserve-3d"}:undefined}><div className="flex min-h-[390px]"><aside className="w-[126px] shrink-0 border-r border-white/[0.055] bg-[#050609] p-2.5"><div className="mb-3 flex h-8 items-center"><LogoMark size="sm" className="!h-5 !w-5"/></div><div className="space-y-0.5">{NAV_ITEMS.map(([id,label])=><div key={id} className={`rounded-md border px-2 py-1.5 text-[6.5px] ${id===activeSection?"border-[#7C4DFF]/35 bg-[#7C4DFF]/20 text-white":"border-transparent text-[#697182]"}`}>{label}</div>)}</div><div className="mt-3 rounded-lg border border-white/[0.06] bg-[#0B0D16] p-2 text-center"><div className="text-[5px] uppercase tracking-wider text-[#687181]">Discipline du jour</div><div className="mt-1.5 text-[13px] font-bold font-numeric" style={{color:accent}}>94<span className="text-[6px] text-[#687181]">/100</span></div></div></aside><main className="min-w-0 flex-1 p-3"><div className="mb-2.5 flex items-center justify-between"><div><div className="text-[10px] font-semibold">{title}</div><div className="mt-0.5 text-[5.5px] text-[#626A7A]">Données de démonstration</div></div><div className="rounded-md border border-white/[0.06] bg-white/[0.03] px-2 py-1 text-[6px] text-[#8B93A3]">30 derniers jours</div></div>{panel}</main></div></div></div>;
}
