import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Calculator, Check, ChevronDown, ListChecks, Plus, Search, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { accountMarkets, EMOTION_INTENSITIES, getInstrumentsForMarket, getVisibleOptions, normalizeJournalPreferences, TRADE_RESULTS } from "@/lib/journalPreferences";
import { calculateDuration, calculatePnl, calculateRMultiple, isFiniteOrBlank, validateTradePrices } from "@/lib/tradeCalculations";
import { useAppSettings } from "@/hooks/useAppSettings";
export { createEmptyTradeForm } from "@/lib/tradeFormModel";

const numberOrNull=value=>value===""||value===null||value===undefined?null:Number(value);
const needsFinalResult=status=>["winner","loser","breakeven","partial"].includes(status);

const FieldError=({id,children})=>children?<p id={id} role="alert" className="mt-1 text-[10px] text-[#FF7A84]">{children}</p>:null;
const control="mt-1.5 w-full rounded-xl border border-white/10 bg-[#0D1020] px-3 py-2.5 text-xs text-white outline-none transition focus:border-[#7C4DFF] focus:ring-2 focus:ring-[#7C4DFF]/10";

const NumberField=({id,label,value,onChange,placeholder,error,step="any",min})=><label htmlFor={id} className="block text-[10px] font-mono uppercase text-[#9CA3AF]">{label}<input id={id} type="number" inputMode="decimal" step={step} min={min} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} className={`${control} ${error?"border-[#F26A70]/60":""}`}/><FieldError id={`${id}-error`}>{error}</FieldError></label>;

const SelectField=({id,label,value,onChange,options,error,placeholder="Sélectionner"})=><label htmlFor={id} className="block text-[10px] font-mono uppercase text-[#9CA3AF]">{label}<select id={id} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} className={`${control} ${error?"border-[#F26A70]/60":""}`}><option value="">{placeholder}</option>{options.map(item=><option key={item.id || item[0]} value={item.value ?? item.label ?? item[0]}>{item.label || item[1]}{item.historical?" (historique)":""}</option>)}</select><FieldError id={`${id}-error`}>{error}</FieldError></label>;

const ChipMulti=({label,options,selected,onChange})=><fieldset><legend className="text-[10px] font-mono uppercase text-[#9CA3AF]">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{options.map(item=>{const active=selected.includes(item.label);return <button type="button" key={item.id} aria-pressed={active} onClick={()=>onChange(active?selected.filter(value=>value!==item.label):[...selected,item.label])} className={`rounded-full border px-3 py-1.5 text-[11px] transition focus:outline-none focus:ring-2 focus:ring-[#7C4DFF]/40 ${active?"border-[#7C4DFF] bg-[#7C4DFF]/15 text-white":"border-white/10 bg-white/[0.025] text-[#8B93A3] hover:border-white/20"}`}>{item.label}</button>})}</div></fieldset>;

const FormSection=({title,subtitle,children,open=false})=><details open={open} className="group rounded-2xl border border-white/[0.07] bg-white/[0.018]"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><span><span className="block text-sm font-semibold">{title}</span>{subtitle&&<span className="mt-1 block text-[10px] text-[#687183]">{subtitle}</span>}</span><ChevronDown className="h-4 w-4 text-[#687183] transition group-open:rotate-180"/></summary><div className="border-t border-white/[0.06] p-4">{children}</div></details>;

export default function TradeFormModal({ form, setForm, accounts, user, checklist, checklistChecks, setChecklistChecks, editingTrade, saving, onClose, onSave }) {
  const nav=useNavigate(); const { settings }=useAppSettings(); const prefs=normalizeJournalPreferences(user?.journal_preferences); const [instrumentSearch,setInstrumentSearch]=useState(""); const [errors,setErrors]=useState({}); const [priceException,setPriceException]=useState(false); const [autoPnlError,setAutoPnlError]=useState("");
  const selectedAccount=accounts.find(account=>account.id===form.account_id);
  const market=form.market_type || (user?.trader_type === "cfd" ? "cfd" : "futures");
  const activeAccounts=accounts.filter(account=>(account.status || "active") === "active" || account.id===form.account_id);
  const filteredAccounts=activeAccounts.filter(account=>{const markets=accountMarkets(account);return markets.length===0 || markets.includes(market)});
  const instruments=getInstrumentsForMarket(market,prefs,form.instrument).filter(item=>item.label.toLowerCase().includes(instrumentSearch.toLowerCase()));
  const sessionOptions=getVisibleOptions(prefs,"sessions",[form.session]); const setupOptions=getVisibleOptions(prefs,"setups",form.setups); const emotionOptions=getVisibleOptions(prefs,"emotions",[form.emotion,form.emotion_secondary]); const durationOptions=getVisibleOptions(prefs,"durations",[form.duration]); const mistakeOptions=getVisibleOptions(prefs,"mistakes",form.mistakes); const exitOptions=getVisibleOptions(prefs,"exitReasons",[form.exit_reason]); const tagOptions=getVisibleOptions(prefs,"tags",form.tags); const noteSuggestions=getVisibleOptions(prefs,"noteSuggestions");
  const warnings=useMemo(()=>validateTradePrices({entry:form.entry,stop:form.stop,takeProfit:form.take_profit,direction:form.direction}),[form.entry,form.stop,form.take_profit,form.direction]);
  const calculatedR=useMemo(()=>calculateRMultiple({entry:form.entry,stop:form.stop,exit:form.exit_price,direction:form.direction}),[form.entry,form.stop,form.exit_price,form.direction]);
  const requiredChecklist=checklist.filter(item=>item.enabled!==false && item.required); const checklistComplete=requiredChecklist.every(item=>checklistChecks[item.id]); const planRespected=checklistComplete || (form.plan_override && form.plan_exception_reason.trim());

  useEffect(()=>{const handler=e=>{if(e.key==="Escape"&&!saving)onClose()};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[onClose,saving]);
  useEffect(()=>{const duration=calculateDuration(form.entry_time,form.exit_time);if(duration&&(form.duration!==duration.label||form.duration_minutes!==duration.minutes))setForm(current=>({...current,duration:duration.label,duration_minutes:duration.minutes}))},[form.entry_time,form.exit_time,form.duration,form.duration_minutes,setForm]);

  const changeMarket=next=>{const account=activeAccounts.find(item=>{const markets=accountMarkets(item);return markets.length===0||markets.includes(next)});setForm(current=>({...current,market_type:next,account_id:account?.id||"",instrument:""}));setInstrumentSearch("")};
  const autoPnl=()=>{const pnl=calculatePnl({entry:form.entry,exit:form.exit_price,direction:form.direction,size:form.size,pointValue:form.point_value,commission:form.commission});if(pnl===null){setAutoPnlError("Renseigne entrée, sortie, taille et valeur du point.");return}setAutoPnlError("");setForm(current=>({...current,pnl:String(pnl)}))};
  const validate=()=>{const next={};if(!form.account_id)next.account_id="Choisis un compte réel.";if(!form.instrument)next.instrument="Choisis un instrument.";if(!form.direction)next.direction="Choisis une direction.";if(!form.date)next.date="La date est obligatoire.";["entry","exit_price","stop","take_profit","size","point_value","commission","pnl"].forEach(key=>{if(!isFiniteOrBlank(form[key]))next[key]="Valeur numérique invalide."});if(needsFinalResult(form.result_status)&&form.pnl==="")next.pnl="Renseigne le P&L réel ou utilise le calcul automatique.";if(warnings.length&&!priceException)next.prices="Confirme l’exception avant d’enregistrer.";if(form.plan_override&&!form.plan_exception_reason.trim())next.plan_exception_reason="Explique pourquoi le plan est considéré comme respecté.";setErrors(next);return Object.keys(next).length===0};
  const submit=e=>{e.preventDefault();if(!validate())return;const payload={...form,setup:form.setups[0]||null,r:calculatedR,plan_respected:Boolean(planRespected),pnl:form.pnl===""?null:Number(form.pnl),entry:numberOrNull(form.entry),exit_price:numberOrNull(form.exit_price),stop:numberOrNull(form.stop),take_profit:numberOrNull(form.take_profit),size:numberOrNull(form.size)??1,point_value:numberOrNull(form.point_value),commission:numberOrNull(form.commission)??0,checklist_results:checklist.filter(item=>item.enabled!==false).map(item=>({id:item.id,label:item.label,checked:Boolean(checklistChecks[item.id]),required:Boolean(item.required)}))};delete payload.plan_override;onSave(payload)};

  return <div role="dialog" aria-modal="true" aria-labelledby="trade-modal-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-2 backdrop-blur-sm sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form onSubmit={submit} className="flex h-[96dvh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#090B13] shadow-[0_30px_100px_rgba(0,0,0,.7)] sm:h-auto sm:max-h-[92vh]">
    <header className="flex shrink-0 items-center justify-between gap-4 border-b border-white/[0.07] bg-[#0A0D17]/95 px-4 py-4 backdrop-blur sm:px-6"><div><h2 id="trade-modal-title" className="text-xl font-bold">{editingTrade?"Modifier le trade":"Nouveau trade"}</h2><p className="mt-1 text-[10px] text-[#687183]">Les champs avancés restent facultatifs.</p></div><button type="button" onClick={onClose} aria-label="Fermer" className="grid h-9 w-9 place-items-center rounded-xl text-[#8B93A3] hover:bg-white/5 hover:text-white focus:ring-2 focus:ring-[#7C4DFF]/40"><X className="h-4 w-4"/></button></header>
    <div className="min-h-0 flex-1 space-y-4 overflow-y-auto overflow-x-hidden p-3 scrollbar-thin sm:p-5">
      <FormSection title="Informations principales" subtitle="Compte, marché, instrument et résultat" open><div className="grid gap-4 sm:grid-cols-2">
        {user?.trader_type==="both"&&<fieldset className="sm:col-span-2"><legend className="text-[10px] font-mono uppercase text-[#9CA3AF]">Type de marché</legend><div className="mt-2 grid grid-cols-2 gap-2">{[["futures","Futures"],["cfd","CFD / Forex"]].map(([id,label])=><button type="button" key={id} aria-pressed={market===id} onClick={()=>changeMarket(id)} className={`w-full rounded-xl border px-4 py-2.5 text-xs ${market===id?"border-[#7C4DFF] bg-[#7C4DFF]/15 text-white":"border-white/10 text-[#8B93A3]"}`}>{label}</button>)}</div></fieldset>}
        <SelectField id="trade-account" label="Compte" value={form.account_id} onChange={value=>{const account=accounts.find(item=>item.id===value);setForm({...form,account_id:value,market_type:account?.market_type||accountMarkets(account)[0]||market})}} options={filteredAccounts.map(account=>({id:account.id,value:account.id,label:`${account.firm} — ${account.name}`}))} error={errors.account_id}/>
        <label htmlFor="trade-instrument-search" className="block text-[10px] font-mono uppercase text-[#9CA3AF]">Instrument<div className="relative"><Search className="absolute left-3 top-[18px] h-3.5 w-3.5 text-[#596172]"/><input id="trade-instrument-search" value={instrumentSearch} onChange={e=>setInstrumentSearch(e.target.value)} placeholder="Rechercher…" className={`${control} pl-9`}/></div><select value={form.instrument} onChange={e=>setForm({...form,instrument:e.target.value})} aria-invalid={Boolean(errors.instrument)} className={`${control} ${errors.instrument?"border-[#F26A70]/60":""}`}><option value="">Choisir un instrument</option>{instruments.map(item=><option key={item.id} value={item.label}>{item.label}{item.historical?" (historique)":""}</option>)}</select><FieldError id="trade-instrument-error">{errors.instrument}</FieldError><button type="button" onClick={()=>{onClose();nav("/app/settings?section=journal")}} className="mt-2 inline-flex items-center gap-1 text-[10px] text-[#B58BFF] hover:text-white"><Plus className="h-3 w-3"/>Ajouter un instrument</button></label>
        <fieldset><legend className="text-[10px] font-mono uppercase text-[#9CA3AF]">Direction</legend><div className="mt-2 grid grid-cols-2 gap-2">{[["long","Achat / Long"],["short","Vente / Short"]].map(([id,label])=><button type="button" key={id} aria-pressed={form.direction===id} onClick={()=>setForm({...form,direction:id})} className={`w-full rounded-xl border px-3 py-2.5 text-xs ${form.direction===id?"border-[#7C4DFF] bg-[#7C4DFF]/15":"border-white/10 text-[#8B93A3]"}`}>{label}</button>)}</div></fieldset>
        <SelectField id="trade-result" label="Résultat du trade" value={form.result_status} onChange={value=>setForm({...form,result_status:value,...(["open","cancelled"].includes(value)?{pnl:"",exit_price:"",exit_time:""}:{})})} options={TRADE_RESULTS}/>
        <label htmlFor="trade-date" className="block text-[10px] font-mono uppercase text-[#9CA3AF]">Date<input id="trade-date" type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={control}/><FieldError id="trade-date-error">{errors.date}</FieldError></label>
      </div></FormSection>

      <FormSection title="Exécution" subtitle="Prix, horaires et calculs automatiques" open><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField id="trade-entry" label="Entrée" value={form.entry} onChange={value=>setForm({...form,entry:value})} error={errors.entry}/><NumberField id="trade-stop" label="Stop loss" value={form.stop} onChange={value=>setForm({...form,stop:value})} error={errors.stop}/><NumberField id="trade-tp" label="Take profit" value={form.take_profit} onChange={value=>setForm({...form,take_profit:value})} error={errors.take_profit}/>{!["open","cancelled"].includes(form.result_status)&&<NumberField id="trade-exit" label="Prix de sortie" value={form.exit_price} onChange={value=>setForm({...form,exit_price:value})} error={errors.exit_price}/>}<NumberField id="trade-size" label="Taille de position" value={form.size} min="0" onChange={value=>setForm({...form,size:value})} error={errors.size}/><label className="block text-[10px] font-mono uppercase text-[#9CA3AF]">R multiple calculé<input readOnly value={calculatedR ?? "—"} className={`${control} cursor-default text-[#B58BFF]`}/></label><label className="block text-[10px] font-mono uppercase text-[#9CA3AF]">Heure d’entrée<input type="time" value={form.entry_time} onChange={e=>setForm({...form,entry_time:e.target.value})} className={control}/></label><label className="block text-[10px] font-mono uppercase text-[#9CA3AF]">Heure de sortie<input type="time" disabled={["open","cancelled"].includes(form.result_status)} value={form.exit_time} onChange={e=>setForm({...form,exit_time:e.target.value})} className={`${control} disabled:opacity-40`}/></label><SelectField id="trade-duration" label="Durée" value={form.duration} onChange={value=>setForm({...form,duration:value,duration_minutes:null})} options={durationOptions}/></div>
        {warnings.length>0&&<div className="mt-4 rounded-xl border border-[#FFB855]/25 bg-[#FFB855]/[0.06] p-3"><div className="flex gap-2 text-xs text-[#E0B96F]"><AlertTriangle className="h-4 w-4 shrink-0"/><div>{warnings.map(warning=><p key={warning}>{warning}</p>)}</div></div><label className="mt-3 flex items-center gap-2 text-[11px] text-[#B5BBC9]"><input type="checkbox" checked={priceException} onChange={e=>setPriceException(e.target.checked)} className="accent-[#7C4DFF]"/>Je confirme cette configuration exceptionnelle.</label><FieldError id="trade-prices-error">{errors.prices}</FieldError></div>}
        {needsFinalResult(form.result_status)&&<div className="mt-4 grid gap-4 rounded-xl border border-white/[0.06] bg-black/20 p-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField id="trade-pnl" label={`P&L réel (${settings.currency})`} value={form.pnl} onChange={value=>setForm({...form,pnl:value})} error={errors.pnl}/><NumberField id="trade-point" label="Valeur du point" value={form.point_value} min="0" onChange={value=>setForm({...form,point_value:value})} error={errors.point_value}/><NumberField id="trade-commission" label="Commissions" value={form.commission} min="0" onChange={value=>setForm({...form,commission:value})} error={errors.commission}/><div className="flex flex-col justify-end"><button type="button" onClick={autoPnl} className="btn-ghost inline-flex w-full items-center justify-center gap-2 text-xs"><Calculator className="h-3.5 w-3.5"/>Calculer automatiquement</button><FieldError id="auto-pnl-error">{autoPnlError}</FieldError></div></div>}
      </FormSection>

      <FormSection title="Contexte" subtitle="Session, setups, erreurs et sortie"><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><SelectField id="trade-session" label="Session" value={form.session} onChange={value=>setForm({...form,session:value})} options={sessionOptions}/><SelectField id="trade-exit-reason" label="Raison de sortie" value={form.exit_reason} onChange={value=>setForm({...form,exit_reason:value})} options={exitOptions}/></div><ChipMulti label="Setups" options={setupOptions} selected={form.setups} onChange={value=>setForm({...form,setups:value})}/><ChipMulti label="Erreurs fréquentes" options={mistakeOptions} selected={form.mistakes} onChange={value=>setForm({...form,mistakes:value})}/><ChipMulti label="Tags" options={tagOptions} selected={form.tags} onChange={value=>setForm({...form,tags:value})}/></div></FormSection>

      <FormSection title="Psychologie" subtitle="Émotion principale, secondaire et intensité"><div className="grid gap-4 sm:grid-cols-2"><SelectField id="trade-emotion" label="Émotion principale" value={form.emotion} onChange={value=>setForm({...form,emotion:value})} options={emotionOptions}/><SelectField id="trade-emotion-secondary" label="Émotion secondaire" value={form.emotion_secondary} onChange={value=>setForm({...form,emotion_secondary:value})} options={emotionOptions}/><fieldset className="sm:col-span-2"><legend className="text-[10px] font-mono uppercase text-[#9CA3AF]">Intensité</legend><div className="mt-2 grid grid-cols-3 gap-2">{EMOTION_INTENSITIES.map(([id,label])=><button type="button" key={id} aria-pressed={form.emotion_intensity===id} onClick={()=>setForm({...form,emotion_intensity:id})} className={`rounded-xl border px-3 py-2.5 text-xs ${form.emotion_intensity===id?"border-[#7C4DFF] bg-[#7C4DFF]/15":"border-white/10 text-[#8B93A3]"}`}>{label}</button>)}</div></fieldset></div></FormSection>

      <FormSection title="Checklist avant trade" subtitle="Le plan est calculé depuis les règles obligatoires"><div className="space-y-2">{checklist.filter(item=>item.enabled!==false).map(item=><button type="button" key={item.id} aria-pressed={Boolean(checklistChecks[item.id])} onClick={()=>setChecklistChecks(current=>({...current,[item.id]:!current[item.id]}))} className="flex w-full items-center gap-3 rounded-xl border border-white/[0.06] bg-[#0B0E18] p-3 text-left"><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-md border ${checklistChecks[item.id]?"border-[#46C99A] bg-[#46C99A] text-[#06130C]":"border-white/15 text-transparent"}`}><Check className="h-3 w-3"/></span><span className="flex-1 text-xs text-[#B5BBC9]">{item.label}</span>{item.required&&<span className="text-[9px] text-[#B58BFF]">Obligatoire</span>}</button>)}</div><div className={`mt-4 rounded-xl border p-3 text-xs ${checklistComplete?"border-[#46C99A]/20 bg-[#46C99A]/[0.06] text-[#7CE9A9]":"border-[#FFB855]/20 bg-[#FFB855]/[0.06] text-[#D8B26A]"}`}><div className="flex items-center gap-2"><ListChecks className="h-4 w-4"/>Plan respecté : <strong>{planRespected?"Oui":"Non"}</strong></div>{!checklistComplete&&<label className="mt-3 flex items-start gap-2 text-[#B5BBC9]"><input type="checkbox" checked={form.plan_override} onChange={e=>setForm({...form,plan_override:e.target.checked})} className="mt-0.5 accent-[#7C4DFF]"/>Considérer exceptionnellement le plan comme respecté</label>}{form.plan_override&&!checklistComplete&&<label className="mt-3 block text-[10px] uppercase text-[#9CA3AF]">Justification<textarea value={form.plan_exception_reason} onChange={e=>setForm({...form,plan_exception_reason:e.target.value})} rows={2} className={`${control} resize-y normal-case`} placeholder="Explique cette exception…"/><FieldError id="plan-exception-error">{errors.plan_exception_reason}</FieldError></label>}</div></FormSection>

      <FormSection title="Notes" subtitle="Facultatives, avec suggestions rapides"><div><div className="flex flex-wrap gap-2">{noteSuggestions.map(item=><button type="button" key={item.id} onClick={()=>setForm({...form,notes:[form.notes,item.label].filter(Boolean).join(form.notes?" · ":"")})} className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-[#8B93A3] hover:border-[#7C4DFF]/40 hover:text-white">+ {item.label}</button>)}</div><label htmlFor="trade-notes" className="mt-4 block text-[10px] font-mono uppercase text-[#9CA3AF]">Notes<textarea id="trade-notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} className={`${control} resize-y`} placeholder="Ajoute un commentaire seulement si nécessaire…"/></label></div></FormSection>
    </div>
    <footer className="sticky bottom-0 flex shrink-0 flex-col-reverse gap-2 border-t border-white/[0.07] bg-[#0A0D17]/95 p-3 backdrop-blur sm:flex-row sm:justify-end sm:px-6 sm:py-4"><button type="button" disabled={saving} onClick={onClose} className="btn-ghost w-full sm:w-auto">Annuler</button><button type="submit" disabled={saving||!form.account_id} className="btn-primary w-full disabled:opacity-40 sm:w-auto">{saving?"Enregistrement…":editingTrade?"Enregistrer les modifications":"Ajouter le trade"}</button></footer>
  </form></div>;
}
