import React, { useState } from "react";
import { adminApi } from "./api";
import { Empty, LoadState, Metric, Page, RefreshButton, Status, formatDate, formatNumber, useAdminData } from "./ui";
export { default as AdminPropFirms } from "./AdminPropFirmsPage";

export function AdminSync() {
  const [status, setStatus] = useState("");
  const state = useAdminData(() => adminApi.sync({ status: status || undefined, per_page: 100 }), [status]);
  return <Page eyebrow="INTÉGRATIONS" title="Synchronisations" description="État réel des connexions et dernières tentatives, sans identifiants de connexion." actions={<RefreshButton onClick={state.reload} />}><div className="admin-filters"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tous les états</option><option value="success">Succès</option><option value="failed">Échec</option><option value="pending">En attente</option></select></div><LoadState {...state} />{state.data && <div className="admin-panel table-panel">{state.data.items.length ? <div className="admin-table-wrap"><table><thead><tr><th>Plateforme</th><th>Compte</th><th>Connexion</th><th>Synchronisation</th><th>Dernier succès</th><th>Erreur</th></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id}><td><strong>{item.platform}</strong><small>{item.provider}</small></td><td>{item.broker_name || "—"}<small>{item.account_number_masked}</small></td><td><Status value={item.connection_status} /></td><td><Status value={item.sync_status} /></td><td>{formatDate(item.last_successful_sync_at)}</td><td>{item.last_error_code || "—"}<small>{item.last_error_message}</small></td></tr>)}</tbody></table></div> : <Empty />}</div>}</Page>;
}

export function AdminEmails() {
  const [status, setStatus] = useState("");
  const state = useAdminData(() => adminApi.emails({ per_page: 100, status: status || undefined }), [status]);
  return <Page eyebrow="MESSAGERIE" title="E-mails" description="Acceptation par le fournisseur et erreurs connues. « Envoyé » ne prétend pas que la boîte du destinataire a livré le message." actions={<RefreshButton onClick={state.reload} />}><div className="admin-filters"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tous les statuts</option><option value="sent">Envoyés</option><option value="failed">Échecs</option><option value="bounced">Rejets</option></select></div><LoadState {...state} />{state.data && <><section className="admin-metrics"><Metric label="Messages journalisés" value={state.data.total} /><Metric label="Échecs connus" value={state.data.failed} tone={state.data.failed ? "red" : "green"} /><Metric label="Fournisseur" value={state.data.provider_configured ? "Configuré" : "Absent"} tone={state.data.provider_configured ? "green" : "red"} /></section><div className="admin-panel table-panel">{state.data.items.length ? <div className="admin-table-wrap"><table><thead><tr><th>Type</th><th>Destinataire</th><th>Fournisseur</th><th>Statut</th><th>Date</th></tr></thead><tbody>{state.data.items.map((item, index) => <tr key={`${item.event}-${item.user_id}-${index}`}><td>{item.type}</td><td>{item.recipient || "—"}</td><td>{item.provider}</td><td><Status value={item.status} /></td><td>{formatDate(item.sent_at || item.created_at)}</td></tr>)}</tbody></table></div> : <Empty />}</div></>}</Page>;
}

export function AdminAtlas() {
  const state = useAdminData(() => adminApi.atlas(30), []); const data = state.data;
  return <Page eyebrow="IA" title="Atlas" description="Monitoring technique uniquement : aucun prompt ni contenu de réponse n’est affiché." actions={<RefreshButton onClick={state.reload} />}><LoadState {...state} />{data && <><section className="admin-metrics"><Metric label="Requêtes" value={formatNumber(data.requests)} /><Metric label="Succès suivis" value={formatNumber(data.success)} tone="green" /><Metric label="Erreurs" value={formatNumber(data.errors)} tone={data.errors ? "red" : "green"} /><Metric label="Latence moyenne" value={data.average_latency_ms ? `${data.average_latency_ms} ms` : "—"} tone="blue" /></section><section className="admin-panel"><div className="admin-panel-head"><div><span>CONFIGURATION</span><h2>{data.model}</h2></div><Status value={data.configured ? "configuré" : "non configuré"} /></div>{data.events?.length ? <div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Statut</th><th>Contexte</th><th>Durée</th><th>Code</th></tr></thead><tbody>{data.events.map((item, index) => <tr key={`${item.created_at}-${index}`}><td>{formatDate(item.created_at)}</td><td><Status value={item.status} /></td><td>{item.tag}</td><td>{item.duration_ms} ms</td><td>{item.error_code || "—"}</td></tr>)}</tbody></table></div> : <Empty />}</section></>}</Page>;
}

export function AdminBacktesting() {
  const state = useAdminData(() => adminApi.backtesting(30), []); const data = state.data;
  return <Page eyebrow="REPLAY" title="Backtest Lab" description="Usage réel du moteur et des datasets privés, sans contenu de stratégie utilisateur." actions={<RefreshButton onClick={state.reload} />}><LoadState {...state} />{data && <><section className="admin-metrics"><Metric label="Sessions" value={data.sessions} /><Metric label="Utilisateurs actifs" value={data.active_users} tone="green" /><Metric label="Terminées" value={data.completed} tone="blue" /><Metric label="Lignes marché" value={formatNumber(data.market_data_rows)} /></section><section className="admin-grid two"><article className="admin-panel"><div className="admin-panel-head"><div><span>COUVERTURE</span><h2>Marchés</h2></div></div>{Object.keys(data.markets).length ? <div className="admin-rank">{Object.entries(data.markets).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div> : <Empty />}</article><article className="admin-panel"><div className="admin-panel-head"><div><span>DONNÉES</span><h2>Fournisseur</h2></div><Status value={data.provider || "aucun"} /></div><p className="admin-note">Données de marché automatiques : {data.automatic_market_data_configured ? "configurées" : "non configurées"}. Aucun fournisseur fictif n’est annoncé.</p></article></section></>}</Page>;
}

export function AdminAnalytics() {
  const state = useAdminData(() => adminApi.analytics(30), []); const data = state.data;
  return <Page eyebrow="PRODUIT" title="Analytics" description="Événements minimaux, sans contenu de journal ni donnée sensible." actions={<RefreshButton onClick={state.reload} />}><LoadState {...state} />{data && <><section className="admin-metrics"><Metric label="Événements" value={formatNumber(data.events)} /><Metric label="Utilisateurs actifs" value={formatNumber(data.active_users)} tone="green" /></section><section className="admin-grid two"><article className="admin-panel"><div className="admin-panel-head"><div><span>FUNNEL</span><h2>Activation</h2></div></div><div className="admin-funnel">{data.funnel.map((item, index) => <div key={item.step}><span>{index + 1}</span><label>{item.step.replaceAll("_", " ")}</label><strong>{formatNumber(item.users)}</strong></div>)}</div></article><article className="admin-panel"><div className="admin-panel-head"><div><span>USAGE</span><h2>Fonctionnalités</h2></div></div>{data.feature_usage.length ? <div className="admin-rank">{data.feature_usage.map((item) => <div key={item.feature}><span>{item.feature}</span><strong>{item.events}</strong></div>)}</div> : <Empty>La collecte minimale démarre après application de la migration.</Empty>}</article></section></>}</Page>;
}

export function AdminSubscriptions() {
  const state = useAdminData(() => adminApi.subscriptions({ per_page: 100 }), []);
  return <Page eyebrow="FACTURATION" title="Abonnements" description="Plans stockés. Aucun MRR n’est calculé sans montants Stripe vérifiés." actions={<RefreshButton onClick={state.reload} />}><LoadState {...state} />{state.data && <div className="admin-panel table-panel">{state.data.items.length ? <div className="admin-table-wrap"><table><thead><tr><th>Utilisateur</th><th>Plan</th><th>Statut</th><th>Comptes</th><th>Trades</th><th>Inscription</th></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id}><td>{item.name}<small>{item.email}</small></td><td><Status value={item.plan || "free"} /></td><td><Status value={item.subscription_status || "inactive"} /></td><td>{item.accounts_count}</td><td>{item.trades_count}</td><td>{formatDate(item.created_at)}</td></tr>)}</tbody></table></div> : <Empty />}</div>}</Page>;
}
