export const IMPORT_PLATFORMS = Object.freeze([
  {
    id: "metatrader-4",
    name: "MetaTrader 4",
    logo: "/brand/platforms/metatrader-4.png",
    logoClass: "h-9",
    formats: ["HTML"],
    marketsFr: "Forex et CFD",
    marketsEn: "Forex and CFDs",
    instructionsFr: "Historique du compte → Enregistrer comme rapport HTML",
    instructionsEn: "Account History → Save as HTML report",
    sourceUrl: "https://www.metatrader4.com/en/trading-platform/help/overview/reports",
  },
  {
    id: "metatrader-5",
    name: "MetaTrader 5",
    logo: "/brand/platforms/metatrader-5.png",
    logoClass: "h-9",
    formats: ["HTML"],
    marketsFr: "Forex, CFD et Futures",
    marketsEn: "Forex, CFDs, and Futures",
    instructionsFr: "Historique → Rapport → Enregistrer en HTML",
    instructionsEn: "History → Report → Save as HTML",
    sourceUrl: "https://www.metatrader5.com/en/terminal/help/trading/report",
  },
  {
    id: "ctrader",
    name: "cTrader",
    logo: "/brand/platforms/ctrader.svg",
    logoClass: "h-9",
    formats: ["CSV"],
    marketsFr: "Forex et CFD",
    marketsEn: "Forex and CFDs",
    instructionsFr: "Historique → Relevé → Enregistrer en CSV",
    instructionsEn: "History → Statement → Save as CSV",
    sourceUrl: "https://help.ctrader.com/ctrader/trading/history/",
  },
  {
    id: "ninjatrader-8",
    name: "NinjaTrader 8",
    logo: "/brand/platforms/ninjatrader.svg",
    logoClass: "h-8",
    formats: ["CSV"],
    marketsFr: "Futures et Forex",
    marketsEn: "Futures and Forex",
    instructionsFr: "Trade Performance → Trades → clic droit → Export CSV",
    instructionsEn: "Trade Performance → Trades → right-click → Export CSV",
    sourceUrl: "https://ninjatrader.com/support/helpGuides/nt8/working_with_data_grids.htm",
  },
  {
    id: "quantower",
    name: "Quantower",
    logo: "/brand/platforms/quantower.svg",
    logoClass: "h-8",
    formats: ["CSV"],
    marketsFr: "Multi-marchés",
    marketsEn: "Multi-market",
    instructionsFr: "Panneau Trades → Export Data → CSV",
    instructionsEn: "Trades panel → Export Data → CSV",
    sourceUrl: "https://help.quantower.com/quantower/portfolio-panels/trades",
  },
  {
    id: "sierra-chart",
    name: "Sierra Chart",
    logo: "/brand/platforms/sierra-chart.png",
    logoClass: "h-8",
    logoSurface: "bg-white/90",
    formats: ["TXT", "CSV"],
    marketsFr: "Futures et multi-marchés",
    marketsEn: "Futures and multi-market",
    instructionsFr: "Trade Activity Log → Trades → File → Save Log As",
    instructionsEn: "Trade Activity Log → Trades → File → Save Log As",
    sourceUrl: "https://www.sierrachart.com/index.php?page=doc/TradeActivityLog.php",
  },
]);

export const IMPORT_FORMATS_IN_VALIDATION = Object.freeze([
  {
    id: "tradovate",
    name: "Tradovate",
    logo: "/brand/platforms/tradovate.ico",
    format: "CSV",
    noteFr: "Rapport de positions exportable ; correspondance des colonnes en validation.",
    noteEn: "Exportable position report; column mapping is being validated.",
    sourceUrl: "https://tradovate.zendesk.com/hc/en-us/articles/16653178768275-How-Can-I-Run-a-Report-Within-Tradovate-s-Platform",
  },
  {
    id: "dxtrade",
    name: "DXtrade",
    logo: "/brand/platforms/dxtrade.png",
    format: "CSV",
    noteFr: "Historique de transactions exportable ; import dédié en préparation.",
    noteEn: "Transaction history can be exported; dedicated import is in preparation.",
    sourceUrl: "https://dx.trade/news/dxtrade-xt-updates-bridgewise-integration-client-area-and-improved-reports/",
  },
  {
    id: "match-trader",
    name: "Match-Trader",
    logo: "/brand/platforms/match-trader.png",
    format: "HTML",
    noteFr: "Historique du compte exportable ; structure HTML en validation.",
    noteEn: "Account history can be exported; HTML structure is being validated.",
    sourceUrl: "https://docs.match-trade.com/docs/release-notes-match-trader/",
  },
]);
