import React, { useEffect, useMemo, useState } from "react";
import { accounts as accountsAPI, dashboard, trades as tradesAPI } from "@/lib/api";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, CalendarDays, Download, RefreshCw, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { useAppSettings } from "@/hooks/useAppSettings";
import TradeCalendar from "@/components/TradeCalendar";

const TABS = ["Vue d'ensemble","Performance","Calendrier","Trades","Temps","Risques","Comportement"];
const EMPTY_METRICS = { winrate:0,profit_factor:0,avg_win:0,avg_loss:0,plan_respect_rate:0 };
const card = "card-elev p-5";
const localDateKey=value=>{const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10)};
const dateKey=value=>value?String(value).slice(0,10):"";

export default function Analytics() {
  const { money, date } = useAppSettings();
  const [data,setData]=useState(null); const [trades,setTrades]=useState([]); const [accounts,setAccounts]=useState([]);
  const [tab,setTab]=useState(TABS[0]); const [period,setPeriod]=useState("30"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [selectedMonth,setSelectedMonth]=useState(()=>localDateKey(new Date()).slice(0,7));
  const [selectedYear,setSelectedYear]=useState(()=>String(new Date().getFullYear()));
  const [customRange,setCustomRange]=useState({start:"",end:""});
  const load=async()=>{setLoading(true);setError("");try{const[d,t,a]=await Promise.all([dashboard(),tradesAPI.list(),accountsAPI.list()]);setData(d.data);setTrades(t.data);setAccounts(a.data)}catch(e){setError(e.response?.data?.detail||"Impossible de charger les statistiques.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const availableYears=useMemo(()=>Array.from(new Set([String(new Date().getFullYear()),...trades.map(t=>dateKey(t.date).slice(0,4)).filter(year=>/^\d{4}$/.test(year))])).sort((a,b)=>Number(b)-Number(a)),[trades]);
  const filtered=useMemo(()=>{
    if(period==="all")return trades;
    if(period==="month")return trades.filter(t=>dateKey(t.date).startsWith(selectedMonth));
    if(period==="year")return trades.filter(t=>dateKey(t.date).startsWith(selectedYear));
    if(period==="custom")return trades.filter(t=>{const key=dateKey(t.date);if(!key)return false;return(!customRange.start||key>=customRange.start)&&(!customRange.end||key<=customRange.end)});
    const min=Date.now()-Number(period)*86400000;
    return trades.filter(t=>!t.date||new Date(t.date).getTime()>=min);
  },[trades,period,selectedMonth,selectedYear,customRange]);
  const stats=useMemo(()=>calculate(filtered,accounts),[filtered,accounts]);
  const equity=useMemo(()=>{let value=0;return [...filtered].sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(t=>({date:t.date,equity:+(value+=Number(t.pnl||0)).toFixed(2)}))},[filtered]);
  const exportLabel=period==="month"?selectedMonth:period==="year"?selectedYear:period==="custom"?`${customRange.start||"debut"}-${customRange.end||"fin"}`:period==="all"?"toute-periode":`${period}j`;
  const download=()=>{if(!filtered.length)return;const keys=["date","instrument","direction","pnl","r","session","setup","plan_respected","account_id"];const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[keys.join(","),...filtered.map(t=>keys.map(k=>esc(t[k])).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`pipsevo-trades-${exportLabel}.csv`;a.click();URL.revokeObjectURL(url)};
  const metrics=data?.metrics||EMPTY_METRICS;

  return <div className="pe-page pe-page-stack max-w-[1600px] mx-auto">
    <div className="pe-page-header"><div><div className="pe-eyebrow">Analyse des données réelles</div><h1 className="pe-page-title mt-2">Statistiques</h1><p className="pe-page-copy mt-1">Explore uniquement les trades enregistrés dans ton journal.</p></div><div className="flex w-full flex-col gap-2 sm:w-auto sm:items-end"><div className="flex flex-wrap items-center gap-2"><div className="hidden h-10 w-10 place-items-center rounded-xl border border-white/[0.08] bg-white/[0.025] text-[#8C73FF] sm:grid"><CalendarDays className="h-4 w-4"/></div><select aria-label="Type de période" value={period} onChange={e=>setPeriod(e.target.value)} className="pe-control min-w-[150px] flex-1 text-xs sm:flex-none"><option value="7">7 derniers jours</option><option value="30">30 derniers jours</option><option value="90">90 derniers jours</option><option value="month">Mois précis</option><option value="year">Année précise</option><option value="custom">Dates personnalisées</option><option value="all">Toute la période</option></select>{period==="month"&&<input aria-label="Mois à analyser" type="month" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="pe-control min-w-[150px] flex-1 text-xs sm:flex-none"/>}{period==="year"&&<select aria-label="Année à analyser" value={selectedYear} onChange={e=>setSelectedYear(e.target.value)} className="pe-control min-w-[120px] flex-1 text-xs sm:flex-none">{availableYears.map(year=><option key={year} value={year}>{year}</option>)}</select>}{period==="custom"&&<><input aria-label="Date de début" title="Date de début" type="date" value={customRange.start} max={customRange.end||undefined} onChange={e=>setCustomRange(range=>({...range,start:e.target.value}))} className="pe-control min-w-[145px] flex-1 text-xs sm:flex-none"/><input aria-label="Date de fin" title="Date de fin" type="date" value={customRange.end} min={customRange.start||undefined} onChange={e=>setCustomRange(range=>({...range,end:e.target.value}))} className="pe-control min-w-[145px] flex-1 text-xs sm:flex-none"/></>}<button disabled={!filtered.length} onClick={download} title="Exporter les trades filtrés en CSV" className="pe-icon-button disabled:opacity-40"><Download className="w-4 h-4"/></button></div><div className="text-[10px] font-medium text-[#747C8B]">{filtered.length} trade{filtered.length>1?"s":""} dans la sélection</div></div></div>
    <div className="overflow-x-auto border-b border-white/[0.06]"><div className="flex min-w-max gap-1">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-3 text-sm transition ${tab===t?"text-white border-b-2 border-[#7C4DFF]":"text-[#7E8798] hover:text-white"}`}>{t}</button>)}</div></div>
    {error&&<div className="rounded-2xl border border-[#FF5252]/25 bg-[#FF5252]/10 p-4 text-sm text-[#FF8A8A] flex justify-between"><span>{error}</span><button onClick={load} className="inline-flex items-center gap-2 text-xs"><RefreshCw className="w-3.5 h-3.5"/>Réessayer</button></div>}
    {loading?<div className="grid md:grid-cols-3 gap-4">{Array.from({length:6}).map((_,i)=><div key={i} className="h-36 card-elev animate-pulse"/>)}</div>:tab==="Calendrier"?<TradeCalendar trades={trades} money={money} formatDate={date}/>:!filtered.length?<Empty/>:<>
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3"><Kpi l="Profit net" v={money(stats.pnl,{signDisplay:"always"})} c={stats.pnl>=0?"#00E676":"#FF5252"}/><Kpi l="Win rate" v={`${stats.winrate}%`} c="#00E676"/><Kpi l="Profit factor" v={stats.profitFactor.toFixed(2)} c="#B58BFF"/><Kpi l="Gain moyen" v={money(stats.avgWin)} c="#00E676"/><Kpi l="Perte moyenne" v={money(stats.avgLoss)} c="#FF5252"/><Kpi l="Plan respecté" v={`${stats.planRate}%`} c="#4F8CFF"/></div>
      {tab==="Vue d'ensemble"&&<Overview equity={equity} stats={stats}/>}
      {tab==="Performance"&&<Performance stats={stats} money={money}/>}
      {tab==="Trades"&&<TradesView trades={filtered} money={money} date={date}/>}
      {tab==="Temps"&&<TimeView stats={stats} money={money}/>}
      {tab==="Risques"&&<RiskView stats={stats} dashboardData={data} money={money}/>}
      {tab==="Comportement"&&<BehaviorView stats={stats} metrics={metrics} money={money}/>}
    </>}
  </div>;
}

function calculate(trades,accounts){const closed=trades.filter(t=>typeof t.pnl==="number"),wins=closed.filter(t=>t.pnl>0),losses=closed.filter(t=>t.pnl<0),rTrades=trades.filter(t=>typeof t.r==="number");const sum=a=>a.reduce((s,t)=>s+Number(t.pnl||0),0);const group=(key)=>Object.values(trades.reduce((o,t)=>{const n=t[key]||"Non renseigné";o[n]??={name:n,pnl:0,trades:0,wins:0};o[n].pnl+=Number(t.pnl||0);o[n].trades++;if(Number(t.pnl)>0)o[n].wins++;return o},{})).sort((a,b)=>b.pnl-a.pnl);const accountPerf=accounts.map(a=>({name:`${a.firm} · ${a.name}`,pnl:Number(a.balance)-Number(a.initial_balance)})).sort((a,b)=>b.pnl-a.pnl);const grossWin=sum(wins),grossLoss=Math.abs(sum(losses));return{pnl:sum(closed),winrate:closed.length?Math.round(wins.length/closed.length*100):0,profitFactor:grossLoss?grossWin/grossLoss:grossWin?grossWin:0,avgWin:wins.length?grossWin/wins.length:0,avgLoss:losses.length?sum(losses)/losses.length:0,planRate:trades.length?Math.round(trades.filter(t=>t.plan_respected).length/trades.length*100):0,avgR:rTrades.length?rTrades.reduce((s,t)=>s+t.r,0)/rTrades.length:null,total:trades.length,wins:wins.length,losses:losses.length,assets:group("instrument"),sessions:group("session"),setups:group("setup"),accounts:accountPerf,days:groupByDay(trades)}}
function groupByDay(trades){const names=["Dim","Lun","Mar","Mer","Jeu","Ven","Sam"];return names.map((name,index)=>({name,pnl:trades.filter(t=>new Date(t.date).getDay()===index).reduce((s,t)=>s+Number(t.pnl||0),0)}))}
const ChartTip={background:"#0F1117",border:"1px solid #252A38",borderRadius:12,fontSize:12};
const Kpi=({l,v,c})=><div className={card}><div className="text-xs text-[#7E8798]">{l}</div><div className="mt-2 text-xl sm:text-2xl font-bold font-numeric" style={{color:c}}>{v}</div></div>;
const Empty=()=> <div className="card-elev py-16 px-5 text-center"><BarChart3 className="w-8 h-8 mx-auto text-[#6B7280]"/><h2 className="mt-4 font-semibold">Pas encore de statistiques</h2><p className="mt-2 text-sm text-[#7E8798]">Ajoute des trades au journal pour générer des analyses fiables.</p><Link to="/app/journal" className="btn-primary inline-block mt-5">Ouvrir le journal</Link></div>;
const Overview=({equity,stats})=><div className="grid lg:grid-cols-3 gap-4"><div className={`${card} lg:col-span-2`}><h2 className="text-sm font-semibold">Évolution du P&amp;L</h2><div className="h-72 mt-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={equity}><defs><linearGradient id="analytics-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7C4DFF" stopOpacity=".55"/><stop offset="1" stopColor="#7C4DFF" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" stroke="#6B7280" fontSize={10}/><YAxis stroke="#6B7280" fontSize={10}/><Tooltip contentStyle={ChartTip}/><Area dataKey="equity" type="monotone" stroke="#B58BFF" fill="url(#analytics-fill)" strokeWidth={2.4}/></AreaChart></ResponsiveContainer></div></div><div className={card}><h2 className="text-sm font-semibold">Résultats</h2><div className="h-48"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:"Gagnants",value:stats.wins},{name:"Perdants",value:stats.losses}]} dataKey="value" innerRadius={50} outerRadius={72} strokeWidth={0}><Cell fill="#00E676"/><Cell fill="#FF5252"/></Pie><Tooltip contentStyle={ChartTip}/></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-5 text-xs"><span className="text-[#00E676]">● {stats.wins} gagnants</span><span className="text-[#FF5252]">● {stats.losses} perdants</span></div></div></div>;
const Performance=({stats,money})=>{
  const activeDays=stats.days.filter(day=>day.pnl!==0);
  const bestDay=activeDays.reduce((best,day)=>!best||day.pnl>best.pnl?day:best,null);
  return <div className="grid gap-4 lg:grid-cols-2"><Ranking title="Performance par actif" rows={stats.assets} money={money}/><Ranking title="Performance par compte" rows={stats.accounts} money={money}/><div className="card-elev p-4 sm:p-5 lg:col-span-2"><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold">Performance par jour de la semaine</h2><p className="mt-1 text-[11px] text-[#6F7787]">P&amp;L cumulé sur la période sélectionnée</p></div>{bestDay&&<div className="shrink-0 text-right"><div className="text-[10px] uppercase tracking-[.12em] text-[#697282]">Meilleur jour</div><div className="mt-1 text-xs font-semibold text-[#00E676]">{bestDay.name} · {money(bestDay.pnl,{signDisplay:"always"})}</div></div>}</div><div className="mt-3 h-[190px] sm:h-[210px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={stats.days} margin={{top:8,right:8,bottom:4,left:0}} barCategoryGap="32%"><CartesianGrid vertical={false} stroke="rgba(255,255,255,.055)" strokeDasharray="3 5"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:"#737B8B",fontSize:11}} dy={7}/><YAxis width={58} axisLine={false} tickLine={false} tick={{fill:"#697282",fontSize:10}} tickFormatter={compactAxis}/><ReferenceLine y={0} stroke="rgba(255,255,255,.18)"/><Tooltip contentStyle={ChartTip} cursor={{fill:"rgba(255,255,255,.025)"}} formatter={value=>[money(value,{signDisplay:"always"}),"P&L"]}/><Bar dataKey="pnl" maxBarSize={44} radius={6}>{stats.days.map((x,i)=><Cell key={i} fill={x.pnl>0?"#00DFA5":x.pnl<0?"#FF5C6C":"#252A36"}/>)}</Bar></BarChart></ResponsiveContainer></div></div></div>;
};
const compactAxis=value=>{const abs=Math.abs(Number(value)||0);if(abs>=1000000)return`${(value/1000000).toFixed(abs>=10000000?0:1)}M`;if(abs>=1000)return`${(value/1000).toFixed(abs>=10000?0:1)}k`;return String(value)};
const Ranking=({title,rows,money})=><div className={card}><h2 className="text-sm font-semibold mb-3">{title}</h2>{rows.length?rows.slice(0,8).map(x=><div key={x.name} className="flex justify-between gap-3 border-t border-white/[0.05] py-3 first:border-0"><span className="text-sm truncate">{x.name}</span><span className="font-numeric text-sm" style={{color:x.pnl>=0?"#00E676":"#FF5252"}}>{money(x.pnl,{signDisplay:"always"})}</span></div>):<p className="py-8 text-center text-xs text-[#7E8798]">Aucune donnée</p>}</div>;
const TradesView=({trades,money,date})=><div className={card}><h2 className="pe-section-title mb-3">Trades de la période</h2><div className="pe-table-shell"><table className="pe-table min-w-[620px]"><thead><tr><th className="text-left">Date</th><th className="text-left">Instrument</th><th className="text-left">Direction</th><th className="text-right">P&amp;L</th><th className="text-right">R</th><th className="text-left">Setup</th></tr></thead><tbody>{trades.map(t=>{const hasPnl=typeof t.pnl==="number";return <tr key={t.id}><td className="text-[#8B93A3]">{date(t.date)}</td><td className="font-medium">{t.instrument}</td><td>{t.direction==="long"?"Achat":"Vente"}</td><td className="text-right font-mono" style={{color:!hasPnl?"#9CA3AF":t.pnl>=0?"#00E676":"#FF5252"}}>{hasPnl?money(t.pnl,{minimumFractionDigits:2,maximumFractionDigits:2,signDisplay:"always"}):"—"}</td><td className="text-right font-mono">{typeof t.r==="number"?`${t.r.toFixed(2)}R`:"—"}</td><td className="text-[#8B93A3]">{t.setup||"—"}</td></tr>})}</tbody></table></div></div>;
const TimeView=({stats,money})=><div className="grid lg:grid-cols-2 gap-4"><Ranking title="Performance par session" rows={stats.sessions} money={money}/><div className={card}><h2 className="text-sm font-semibold">Lecture de la période</h2><p className="mt-3 text-sm leading-relaxed text-[#8B93A3]">Ta meilleure session est <strong className="text-white">{stats.sessions[0]?.name||"non déterminée"}</strong>. Cette conclusion utilise uniquement les trades de la période sélectionnée.</p></div></div>;
const RiskView=({stats,dashboardData,money})=><div className="grid md:grid-cols-3 gap-4"><Kpi l="R moyen" v={stats.avgR===null?"—":`${stats.avgR.toFixed(2)}R`} c={stats.avgR===null?"#9CA3AF":stats.avgR>=0?"#00E676":"#FF5252"}/><Kpi l="Drawdown disponible" v={money(dashboardData?.kpis?.remaining_drawdown||0)} c="#FFB855"/><Kpi l="Respect du plan" v={`${stats.planRate}%`} c="#B58BFF"/></div>;
const BehaviorView=({stats,money})=><div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2"><Ranking title="Performance par setup" rows={stats.setups} money={money}/></div><div className={`${card} glow-purple`}><div className="flex gap-2 items-center font-semibold"><Sparkles className="w-4 h-4 text-[#B58BFF]"/>Analyse IA</div><p className="mt-3 text-xs leading-relaxed text-[#8B93A3]">Demande à Atlas d’analyser ces résultats et de proposer un plan comportemental.</p><Link to="/app/coach" className="btn-primary block text-center mt-5 text-xs">Ouvrir l’analyse IA</Link></div></div>;
