import React, { useEffect, useMemo, useState } from "react";
import { dashboard, trades as tradesAPI, accounts as accountsAPI } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { AlertTriangle, CheckCircle2, RefreshCw, XCircle } from "lucide-react";
import { useAppSettings } from "@/hooks/useAppSettings";
import { evaluateRiskAlerts } from "@/lib/riskEngine";

export default function Discipline() {
  const { user }=useAuth(); const { money }=useAppSettings(); const [d,setD]=useState(null); const [trades,setTrades]=useState([]); const [accounts,setAccounts]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const[a,b,c]=await Promise.all([dashboard(),tradesAPI.list(),accountsAPI.list()]);setD(a.data);setTrades(b.data);setAccounts(c.data)}catch(e){setError(e.response?.data?.detail||"Impossible de charger la discipline.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const rules=useMemo(()=>user?.rules||{},[user?.rules]); const k=d?.kpis||{discipline_score:0,total_trades:0}; const m=d?.metrics||{plan_respect_rate:0};
  const insight=useMemo(()=>{const today=new Date().toISOString().slice(0,10);const todays=trades.filter(t=>t.date===today);const todayPnl=todays.reduce((s,t)=>s+Number(t.pnl||0),0);let consecutive=0;for(const t of [...trades].sort((a,b)=>String(b.date).localeCompare(String(a.date)))){if(Number(t.pnl)<0)consecutive++;else break}const violations=trades.filter(t=>t.plan_respected===false).length;return{todayCount:todays.length,todayPnl,consecutive,violations}},[trades]);
  const maxTrades=Number(rules.max_trades||3),dailyLimit=Number(rules.daily_loss_limit||0),stopAfter=Number(rules.stop_after_loss||2);
  const riskAlerts=useMemo(()=>evaluateRiskAlerts({accounts,trades,rules}),[accounts,trades,rules]);
  const hasMeasuredPlan = m.plan_respect_rate !== null && m.plan_respect_rate !== undefined;
  const ruleCards=[{ok:insight.todayCount<=maxTrades,label:"Nombre de trades",sub:`${insight.todayCount}/${maxTrades} trades aujourd’hui`},{ok:dailyLimit<=0||insight.todayPnl>=-dailyLimit,label:"Limite de perte quotidienne",sub:dailyLimit>0?`P&L du jour ${money(insight.todayPnl,{signDisplay:"always"})} · limite ${money(-dailyLimit)}`:"Aucune limite configurée"},{ok:insight.consecutive<stopAfter,label:"Stop après pertes",sub:`${insight.consecutive} perte${insight.consecutive>1?"s":""} consécutive${insight.consecutive>1?"s":""} · limite ${stopAfter}`},{ok:hasMeasuredPlan ? Number(m.plan_respect_rate)>=80 : null,label:"Plan respecté",sub:hasMeasuredPlan?`${Number(m.plan_respect_rate).toFixed(0)}% des trades renseignés`:"Pas encore mesuré"}];
  if(loading)return <div className="pe-page grid gap-4 md:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="pe-card h-40 animate-pulse"/>)}</div>;
  return <div className="pe-page pe-page-stack mx-auto max-w-[1500px]"><div className="pe-page-header"><div><div className="pe-eyebrow">Règles personnalisées</div><h1 className="pe-page-title">Discipline Engine</h1><p className="pe-page-copy">Calculé depuis tes règles d’onboarding et tes trades réels.</p></div></div>
    {error&&<div className="rounded-2xl border border-[#FF5252]/25 bg-[#FF5252]/10 p-4 text-sm text-[#FF8A8A] flex justify-between"><span>{error}</span><button onClick={load} className="inline-flex items-center gap-2 text-xs"><RefreshCw className="w-3.5 h-3.5"/>Réessayer</button></div>}
    {riskAlerts.length>0&&<section className="card-elev overflow-hidden"><div className="border-b border-white/[0.07] p-5"><div className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="h-4 w-4 text-[#FFB855]"/>Alertes de risque actives</div><p className="mt-1 text-xs text-[#7E8798]">Calculées uniquement depuis les limites enregistrées sur tes comptes.</p></div><div className="grid gap-2 p-4 sm:grid-cols-2">{riskAlerts.map((alert,index)=><div key={`${alert.accountId}-${alert.title}-${index}`} className={`rounded-xl border p-4 ${alert.severity==="critical"?"border-[#FF5252]/25 bg-[#FF5252]/[0.07]":"border-[#FFB855]/25 bg-[#FFB855]/[0.06]"}`}><div className={`text-sm font-semibold ${alert.severity==="critical"?"text-[#FF7B84]":"text-[#FFD080]"}`}>{alert.title}</div><p className="mt-1 text-xs text-[#A5ADBA]">{alert.detail}</p></div>)}</div></section>}
    {!trades.length?<div className="card-elev py-16 px-5 text-center"><AlertTriangle className="w-8 h-8 mx-auto text-[#FFB855]"/><h2 className="mt-4 font-semibold">Discipline non mesurable</h2><p className="mt-2 text-sm text-[#7E8798]">Journalise au moins un trade pour calculer ton score.</p></div>:<><div className="grid lg:grid-cols-3 gap-4"><div className="card-elev p-8 text-center glow-purple"><div className="text-[11px] font-mono uppercase tracking-widest text-[#9CA3AF]">Score de discipline</div><div className="my-5"><BigGauge value={Number(k.discipline_score||0)}/></div><div className="text-sm text-[#B58BFF]">{hasMeasuredPlan ? k.discipline_score>=80?"Excellent":k.discipline_score>=60?"À consolider":"Priorité discipline" : "En attente de données"}</div></div><div className="card-elev p-6 lg:col-span-2"><div className="text-sm font-semibold mb-4">Règles du jour</div><div className="grid sm:grid-cols-2 gap-3">{ruleCards.map(r=><RuleCard key={r.label}{...r}/>)}</div></div></div><div className="grid md:grid-cols-3 gap-4"><Metric label="Trades hors plan" value={insight.violations} sub="Sur tout l’historique" color={insight.violations?"#FF5252":"#00E676"}/><Metric label="Pertes consécutives" value={insight.consecutive} sub={`Arrêt recommandé à ${stopAfter}`} color={insight.consecutive>=stopAfter?"#FF5252":"#FFB855"}/><Metric label="Plan respecté" value={hasMeasuredPlan?`${Number(m.plan_respect_rate).toFixed(0)}%`:"—"} sub={hasMeasuredPlan?`${k.total_trades||trades.length} trades analysés`:"À renseigner dans le journal"} color={hasMeasuredPlan?"#B58BFF":"#7E8798"}/></div></>}
  </div>;
}
const RuleCard=({ok,label,sub})=><div className="card-flat flex min-h-20 items-start gap-3 p-4">{ok===null?<AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-[#7E8798]"/>:ok?<CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#00E676]"/>:<XCircle className="mt-0.5 h-5 w-5 shrink-0 text-[#FF5252]"/>}<div><div className="text-sm font-semibold">{label}</div><div className="mt-1 text-xs leading-relaxed text-[#9CA3AF]">{sub}</div></div></div>;
const Metric=({label,value,sub,color})=><div className="pe-card pe-card-pad"><div className="text-sm font-semibold">{label}</div><div className="font-numeric mt-3 text-4xl font-bold" style={{color}}>{value}</div><div className="mt-2 text-xs text-[#7E8798]">{sub}</div></div>;
function BigGauge({value}){const pct=Math.max(0,Math.min(1,value/100));return <div className="relative w-52 h-32 mx-auto"><svg viewBox="0 0 200 110" className="w-full h-full"><defs><linearGradient id="dg-grad" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#7C4DFF"/><stop offset="100%" stopColor="#B58BFF"/></linearGradient></defs><path d="M20 95 A75 75 0 0 1 180 95" stroke="#1E2430" strokeWidth="14" fill="none" strokeLinecap="round"/><path d="M20 95 A75 75 0 0 1 180 95" stroke="url(#dg-grad)" strokeWidth="14" fill="none" strokeLinecap="round" strokeDasharray="236" strokeDashoffset={236-236*pct}/></svg><div className="absolute inset-0 flex items-end justify-center pb-2 text-4xl font-bold font-mono">{value}<span className="text-sm text-[#9CA3AF]">/100</span></div></div>}
