import React, { useEffect, useMemo, useState } from "react";
import { BarChart3, Calculator, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import TradingViewChart from "@/components/TradingViewChart";
import { useAuth } from "@/context/AuthContext";

const MARKET_GROUPS={cfd:[{label:"EUR/USD",symbol:"OANDA:EURUSD"},{label:"Or CFD",symbol:"OANDA:XAUUSD"},{label:"Nasdaq CFD",symbol:"NASDAQ:NDX"},{label:"Bitcoin CFD",symbol:"BINANCE:BTCUSDT"}],futures:[{label:"Nasdaq Futures",symbol:"CME_MINI:NQ1!"},{label:"S&P Futures",symbol:"CME_MINI:ES1!"},{label:"Or Futures",symbol:"COMEX:GC1!"},{label:"Pétrole Futures",symbol:"NYMEX:CL1!"}]};
export default function MarketTerminal(){
  const {user}=useAuth(); const markets=useMemo(()=>user?.trader_type==="both"?[...MARKET_GROUPS.futures,...MARKET_GROUPS.cfd]:MARKET_GROUPS[user?.trader_type]||MARKET_GROUPS.futures,[user?.trader_type]);
  const [market,setMarket]=useState(markets[0]); const [interval,setInterval]=useState("60");
  const [calc,setCalc]=useState({capital:50000,risk:1,stop:20,value:10});
  const [checks,setChecks]=useState(()=>{try{return JSON.parse(localStorage.getItem("pipsevo_pretrade_checks"))||[false,false,false,false]}catch{return[false,false,false,false]}});
  useEffect(()=>{if(!markets.some(m=>m.symbol===market.symbol))setMarket(markets[0])},[markets,market.symbol]);
  useEffect(()=>{localStorage.setItem("pipsevo_pretrade_checks",JSON.stringify(checks))},[checks]);
  const riskAmount=useMemo(()=>+calc.capital*(+calc.risk/100),[calc]);
  const lots=useMemo(()=>riskAmount/Math.max(0.01,+calc.stop*+calc.value),[riskAmount,calc]);
  const toggle=i=>setChecks(c=>c.map((x,n)=>n===i?!x:x));
  return <div className="p-4 sm:p-7 space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><h1 className="text-2xl sm:text-3xl font-bold flex items-center gap-2"><BarChart3 className="text-[#B58BFF]"/>Marchés</h1><p className="text-sm text-[#9CA3AF] mt-1">Analyse le contexte, calcule ton risque, puis documente ta décision.</p></div><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer" className="btn-ghost inline-flex items-center gap-2 text-sm">Ouvrir TradingView <ExternalLink className="w-4 h-4"/></a></div>
    <div className="card-elev p-3 sm:p-5"><div className="flex flex-col lg:flex-row justify-between gap-3 mb-4"><div className="flex gap-2 overflow-x-auto">{markets.map(x=><button key={x.symbol} onClick={()=>setMarket(x)} className={`px-3 py-2 rounded-xl text-xs whitespace-nowrap ${market.symbol===x.symbol?"bg-[#7C4DFF]/20 border border-[#7C4DFF]/50":"border border-white/5 text-[#9CA3AF]"}`}>{x.label}</button>)}</div><div className="flex gap-1">{[["15","15m"],["60","1h"],["240","4h"],["D","1j"]].map(([v,l])=><button key={v} onClick={()=>setInterval(v)} className={`px-3 py-1.5 rounded-lg text-xs ${interval===v?"bg-white/10":"text-[#6B7280]"}`}>{l}</button>)}</div></div><div className="h-[430px] sm:h-[620px] rounded-xl overflow-hidden border border-white/10 bg-[#131722]"><TradingViewChart symbol={market.symbol} interval={interval}/></div></div>
    <div className="grid lg:grid-cols-2 gap-4">
      <div className="card-elev p-6"><div className="flex items-center gap-2 font-semibold"><Calculator className="w-5 h-5 text-[#4F8CFF]"/>Calculateur de position</div><div className="grid sm:grid-cols-2 gap-3 mt-5">{[["capital","Capital du compte ($)"],["risk","Risque (%)"],["stop","Stop loss (points/pips)"],["value","Valeur d'un point par lot ($)"]].map(([k,l])=><label key={k} className="text-xs text-[#9CA3AF]">{l}<input type="number" min="0.01" step="0.01" value={calc[k]} onChange={e=>setCalc({...calc,[k]:e.target.value})} className="mt-1 w-full bg-[#0D1020] border border-white/10 rounded-xl px-3 py-2.5 text-white"/></label>)}</div><div className="grid grid-cols-2 gap-3 mt-5"><Out label="Montant risqué" value={`$${riskAmount.toFixed(2)}`} color="#FFB855"/><Out label="Taille estimée" value={`${lots.toFixed(2)} lots`} color="#4F8CFF"/></div><p className="text-[10px] text-[#6B7280] mt-4">Estimation uniquement : vérifie la valeur du point et les spécifications de ton courtier.</p></div>
      <div className="card-elev p-6"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="w-5 h-5 text-[#00E676]"/>Check-list avant trade</div><div className="space-y-3 mt-5">{["Le setup correspond à mon plan","Le risque respecte ma limite","Le ratio rendement/risque est acceptable","Je ne trade pas pour récupérer une perte"].map((x,i)=><button key={x} onClick={()=>toggle(i)} className={`w-full text-left flex items-center gap-3 p-3 rounded-xl border ${checks[i]?"border-[#00E676]/40 bg-[#00E676]/5":"border-white/5 bg-white/[0.02]"}`}><CheckCircle2 className={`w-5 h-5 ${checks[i]?"text-[#00E676]":"text-[#374151]"}`}/><span className="text-sm">{x}</span></button>)}</div><div className="mt-5 h-2 rounded-full bg-white/5 overflow-hidden"><div className="h-full bg-[#00E676] transition-all" style={{width:`${checks.filter(Boolean).length/4*100}%`}}/></div><div className="text-xs text-[#9CA3AF] mt-2">{checks.filter(Boolean).length}/4 conditions validées</div></div>
    </div>
    <p className="text-[10px] text-[#6B7280]">Les graphiques sont fournis par TradingView. PipsEvo ne fournit aucun signal, conseil financier ou recommandation d'investissement.</p>
  </div>;
}
const Out=({label,value,color})=><div className="card-flat p-4"><div className="text-xs text-[#9CA3AF]">{label}</div><div className="text-xl font-bold font-mono mt-2" style={{color}}>{value}</div></div>;
