import React, { useState } from "react";
import { Link } from "react-router-dom";
import { Check, Mail, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";
import { contact } from "@/lib/api";
import { toast } from "sonner";
import { openCookieSettings } from "@/components/CookieConsent";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const faqs = [
  ["Comment ajouter mes trades ?", "Depuis le Journal, clique sur Nouveau trade, choisis ton compte puis renseigne le résultat et le contexte du trade."],
  ["Quelles prop firms sont compatibles ?", "La saisie guidée couvre actuellement Topstep, Apex, FTMO, FundedNext, The5ers et Take Profit Trader. Leur présence dans PipsEvo indique une compatibilité de suivi, pas un partenariat officiel."],
  ["PipsEvo donne-t-il des signaux ?", "Non. Le service analyse uniquement tes performances, ta discipline et tes habitudes."],
  ["Mes données sont-elles privées ?", "Tes données sont associées à ton compte et les routes privées nécessitent une authentification."],
  ["Puis-je utiliser plusieurs comptes ?", "Oui. Le plan bêta permet de centraliser plusieurs comptes et de filtrer les résultats par compte."],
  ["Comment fonctionne le coach IA ?", "Il s'appuie sur tes derniers trades pour proposer une analyse comportementale, jamais des ordres d'achat ou de vente."],
  ["Puis-je résilier à tout moment ?", "Aucun abonnement payant n'est proposé pendant la bêta. Les modalités de résiliation seront affichées clairement avant toute future souscription."],
];

function PublicLayout({ title, subtitle, children }) {
  return <div className="min-h-screen bg-[#050505] text-white">
    <header className="border-b border-white/5 bg-[#050505]/90 backdrop-blur-xl"><div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between"><Logo/><nav className="flex items-center gap-2 sm:gap-4 text-sm text-[#9CA3AF]"><Link to="/pricing" className="hidden sm:inline hover:text-white">Tarifs</Link><Link to="/faq" className="hidden sm:inline hover:text-white">FAQ</Link><Link to="/contact" className="hidden md:inline hover:text-white">Contact</Link><LanguageSwitcher compact/><Link to="/login" className="btn-primary py-2">Connexion</Link></nav></div></header>
    <main className="max-w-5xl mx-auto px-5 py-14"><div className="text-center mb-10"><h1 className="text-3xl sm:text-5xl font-bold text-gradient">{title}</h1><p className="text-[#9CA3AF] mt-3 max-w-2xl mx-auto">{subtitle}</p></div>{children}</main>
    <Footer/>
  </div>;
}

export function FAQPage(){return <PublicLayout title="Questions fréquentes" subtitle="Tout ce qu'il faut savoir pour utiliser PipsEvo."><div className="max-w-3xl mx-auto space-y-3">{faqs.map(([q,a])=><details key={q} className="card-flat p-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="text-sm text-[#9CA3AF] mt-3 leading-relaxed">{a}</p></details>)}</div></PublicLayout>}

export function ContactPage(){
  const [form,setForm]=useState({name:"",email:"",subject:"",message:""}); const [sending,setSending]=useState(false);
  const submit=async(e)=>{e.preventDefault();setSending(true);try{await contact(form);toast.success("Message envoyé");setForm({name:"",email:"",subject:"",message:""})}catch(e){toast.error(e.response?.data?.detail || "Envoi impossible")}finally{setSending(false)}};
  const field=(k,label,type="text",autoComplete)=><label htmlFor={`contact-${k}`} className="block text-xs text-[#9CA3AF]">{label}<input id={`contact-${k}`} name={k} type={type} autoComplete={autoComplete} required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-2 w-full bg-[#0D1020] border border-white/10 rounded-xl px-4 py-3 text-white outline-none focus:border-[#7C4DFF]"/></label>;
  return <PublicLayout title="Contacte-nous" subtitle="Une question, une difficulté ou une suggestion ? Notre équipe te répond."><div className="grid md:grid-cols-3 gap-5"><div className="card-elev p-6 space-y-4"><Mail className="text-[#B58BFF]"/><div><div className="font-semibold">Support</div><div className="text-sm text-[#9CA3AF] mt-1">Réponse habituelle sous 1 à 2 jours ouvrés.</div></div><a href="mailto:support@pipsevo.app" className="text-sm text-[#B58BFF] hover:text-white">support@pipsevo.app</a></div><form onSubmit={submit} className="card-elev p-6 md:col-span-2 space-y-4">{field("name","Ton nom","text","name")}{field("email","Ton e-mail","email","email")}{field("subject","Sujet")}<label htmlFor="contact-message" className="block text-xs text-[#9CA3AF]">Message<textarea id="contact-message" name="message" required minLength={10} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows={6} className="mt-2 w-full bg-[#0D1020] border border-white/10 rounded-xl px-4 py-3 text-white outline-none focus:border-[#7C4DFF] resize-y"/></label><button disabled={sending} className="btn-primary w-full disabled:opacity-50">{sending?"Envoi…":"Envoyer le message"}</button><p className="text-[10px] text-[#6B7280]">Les informations envoyées servent uniquement à traiter ta demande.</p></form></div></PublicLayout>;
}

export function PricingPage(){return <PublicLayout title="Gratuit pendant la bêta" subtitle="Aucune carte bancaire et aucun prélèvement pendant la période bêta."><div className="grid md:grid-cols-2 gap-5 max-w-3xl mx-auto"><Plan current name="Accès bêta" price="0 €" note="Toutes les fonctions actuellement disponibles" items={["Comptes et trades manuels","Journal et statistiques","Discipline et payouts","Atlas selon disponibilité"]}/><Plan name="Pro — après la bêta" price="19,99 €/mois" note="Prix prévu, confirmé avant toute facturation" disabled items={["Comptes illimités","Atlas","Imports avancés prévus","Support prioritaire"]}/></div><p className="max-w-2xl mx-auto text-center text-xs text-[#6B7280] mt-6">Aucun abonnement payant ne peut actuellement être souscrit sur PipsEvo.</p></PublicLayout>}
const Plan=({name,price,note,items,current,disabled})=><div className={`card-elev p-7 ${current?"glow-purple border-[#7C4DFF]/40":""} ${disabled?"opacity-75":""}`}><div className="text-[#B58BFF] font-mono uppercase text-xs">{name}</div><div className="text-4xl font-bold mt-3">{price}</div><div className="text-xs text-[#9CA3AF] mt-2">{note}</div><div className="space-y-3 mt-6">{items.map(x=><div key={x} className="flex gap-2 text-sm"><Check className={`w-4 h-4 ${current?"text-[#00E676]":"text-[#6B7280]"}`}/>{x}</div>)}</div>{disabled?<button disabled className="btn-ghost w-full mt-7 opacity-60 cursor-not-allowed">Bientôt disponible</button>:<Link to="/register" className="btn-primary block text-center mt-7">Rejoindre la bêta</Link>}</div>;

const legal = {
  privacy:{title:"Politique de confidentialité",intro:"Comprendre quelles données sont utilisées et garder le contrôle sur tes choix.",sections:[
    ["Données traitées","PipsEvo traite les informations nécessaires à ton compte : nom affiché, adresse e-mail, préférences d’onboarding, comptes de trading, trades, règles, payouts et conversations enregistrées avec Atlas."],
    ["Finalités","Ces données servent à authentifier ton compte, fournir les tableaux de bord, calculer tes statistiques et répondre aux demandes adressées au support. Elles ne sont pas vendues."],
    ["Statistiques facultatives","PostHog n’est chargé qu’après ton accord. L’autocapture et l’enregistrement de session sont désactivés. Tu peux refuser ou modifier ce choix à tout moment."],
    ["Hébergement et prestataires","Le frontend est hébergé par Vercel et l’API par Render. Certains traitements peuvent également dépendre du fournisseur de base de données et du service IA utilisé par Atlas."],
    ["Conservation et droits","Les données sont conservées pour fournir le service tant que le compte est actif. Tu peux demander l’accès, la rectification, l’export ou la suppression de tes informations en contactant support@pipsevo.app."],
  ]},
  terms:{title:"Conditions d’utilisation",intro:"Règles applicables à l’utilisation de la version bêta de PipsEvo.",sections:[
    ["Objet du service","PipsEvo est un outil de journalisation et d’analyse comportementale. Il ne fournit ni conseil financier, ni signal, ni recommandation d’achat ou de vente."],
    ["Version bêta","Le service peut évoluer, être interrompu ou contenir des erreurs. L’accès est actuellement gratuit et aucun paiement ne peut être souscrit pendant la bêta."],
    ["Responsabilité de l’utilisateur","Tu restes seul responsable de tes décisions, de tes comptes de trading, des informations saisies et de la sécurité de tes identifiants."],
    ["Utilisation acceptable","Il est interdit de compromettre le service, contourner ses protections, automatiser des accès abusifs ou utiliser PipsEvo pour promouvoir des rendements garantis."],
    ["Disponibilité et suppression","PipsEvo ne garantit pas une disponibilité permanente. Un compte peut être suspendu en cas d’abus. Une demande de suppression peut être transmise au support."],
  ]},
  security:{title:"Sécurité",intro:"Mesures appliquées et bonnes pratiques pour protéger ton espace.",sections:[
    ["Protection du compte","Les mots de passe sont hachés et ne sont pas enregistrés en clair. Les routes privées exigent un jeton d’authentification."],
    ["Transport et accès","Les services déployés utilisent HTTPS. Les données d’un utilisateur sont filtrées par son identifiant côté API."],
    ["Bonnes pratiques","Utilise un mot de passe unique, ne partage jamais ton jeton de connexion et déconnecte-toi des appareils partagés."],
    ["Signalement","En cas d’activité suspecte ou de vulnérabilité, contacte support@pipsevo.app sans publier les détails sensibles."],
    ["Limites actuelles","La double authentification et la gestion avancée des sessions ne sont pas encore disponibles pendant la bêta."],
  ]},
  affiliate:{title:"Conditions du programme partenaire",intro:"Le programme n’est pas encore ouvert commercialement.",sections:[
    ["Statut du programme","Les candidatures servent uniquement à manifester un intérêt. Aucun lien rémunéré ni commission n’est actuellement garanti."],
    ["Communication responsable","Un futur partenaire devra présenter PipsEvo honnêtement, sans promettre de gains, de réussite en prop firm ou de performance financière."],
    ["Conditions futures","Les commissions, seuils, modalités de paiement et règles de marque feront l’objet de conditions distinctes avant l’ouverture du programme."],
    ["Fraude et abus","Toute fraude, publicité trompeuse, usurpation de marque ou manipulation des inscriptions entraînera un refus ou une suspension."],
  ]},
};
export function LegalPage({type}){const page=legal[type];return <PublicLayout title={page.title} subtitle={page.intro}><div className="card-elev p-6 sm:p-8 max-w-3xl mx-auto"><div className="flex items-center justify-between gap-3 border-b border-white/[0.07] pb-5"><ShieldCheck className="text-[#B58BFF]"/><span className="text-[10px] text-[#6B7280]">Mise à jour : 13 juillet 2026</span></div><div className="mt-6 space-y-7">{page.sections.map(([heading,text])=><section key={heading}><h2 className="font-semibold">{heading}</h2><p className="text-sm text-[#B5BBC9] mt-2 leading-relaxed">{text}</p></section>)}</div>{type==="privacy"&&<button onClick={openCookieSettings} className="btn-ghost mt-8">Gérer mes préférences de cookies</button>}</div></PublicLayout>}

export function PlatformsPage(){const ps=[["Saisie manuelle","Disponible","Ajoute immédiatement tes comptes et trades depuis le journal."],["Import CSV","En préparation","Prévisualisation, validation et détection des doublons avant import."],["MetaTrader 4 / 5","À l’étude","Aucune synchronisation directe n’est encore disponible."],["cTrader","À l’étude","La faisabilité dépendra des accès et autorisations officielles."],["Tradovate / NinjaTrader","À l’étude","Intégrations envisagées pour les traders Futures."]];return <PublicLayout title="Plateformes et imports" subtitle="La saisie manuelle est disponible. Les imports et connexions directes ne le sont pas encore."><div className="grid sm:grid-cols-2 gap-4">{ps.map(([n,s,d])=><div key={n} className="card-elev p-6"><div className="flex justify-between gap-3"><h2 className="font-semibold">{n}</h2><span className="text-[10px] text-[#B58BFF] border border-[#7C4DFF]/30 rounded-full px-2 py-1 whitespace-nowrap">{s}</span></div><p className="text-sm text-[#9CA3AF] mt-3">{d}</p></div>)}</div><div className="mt-6 rounded-2xl border border-[#FFB855]/20 bg-[#FFB855]/5 p-4 text-xs text-[#B5BBC9]">Les noms de plateformes et prop firms indiquent une compatibilité de saisie ou une piste d’intégration. Ils n’impliquent aucun partenariat officiel.</div></PublicLayout>}

const posts=[
  {title:"Construire un journal de trading utile",intro:"Un bon journal relie le résultat, le contexte, l'émotion et le respect du plan.",steps:["Note le setup et la raison d'entrée avant d'évaluer le résultat.","Ajoute le risque prévu, le résultat en R et le respect de tes règles.","Relis chaque semaine les erreurs qui se répètent, pas seulement les pertes."]},
  {title:"Comprendre le drawdown d'une prop firm",intro:"Mesure le drawdown consommé avant de chercher à accélérer les gains.",steps:["Identifie si la limite est fixe, quotidienne ou suiveuse.","Calcule ton coussin restant avant chaque nouvelle session.","Réduis le risque quand la marge de sécurité diminue au lieu de tenter de te refaire."]},
  {title:"Pourquoi suivre son R multiple",intro:"Le R multiple compare des trades malgré des tailles de position différentes.",steps:["Définis 1R comme le montant réellement risqué au départ.","Exprime chaque gain ou perte en multiple de ce risque.","Compare ensuite les setups sur une série suffisante, jamais sur un seul trade."]},
  {title:"Éviter le revenge trading",intro:"Une règle simple après une perte protège mieux qu'une décision prise sous pression.",steps:["Impose une pause mesurable après une perte ou une violation de règle.","Note l'émotion et l'urgence ressenties avant toute nouvelle entrée.","Mesure le coût des trades pris hors plan pour rendre le pattern visible."]},
  {title:"Préparer une demande de payout",intro:"Un payout durable dépend autant de la régularité que du profit brut.",steps:["Relis les règles officielles et les jours minimum de ta firme.","Vérifie le coussin de drawdown qui restera après le retrait.","Conserve une trace de la demande et du montant réellement reçu."]},
  {title:"Utiliser un backtest sans se mentir",intro:"Un backtest crédible inclut aussi les périodes difficiles et les frais.",steps:["Définis les règles avant de commencer et ne les change pas au milieu du test.","Teste plusieurs contextes de marché avec un échantillon suffisant.","Compare espérance, drawdown et séries de pertes avant de passer en conditions réelles."]},
];
export function BlogPage(){return <PublicLayout title="Guides PipsEvo" subtitle="Des méthodes concrètes sur la discipline, l'analyse et les comptes financés."><div className="grid md:grid-cols-2 gap-4">{posts.map((post,i)=><details key={post.title} className="card-elev p-6 group"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] text-[#B58BFF] font-mono">GUIDE {String(i+1).padStart(2,"0")} · 3 MIN</div><h2 className="font-semibold text-lg mt-3">{post.title}</h2></div><span className="text-[#B58BFF] text-xl transition-transform group-open:rotate-45">+</span></div><p className="text-sm text-[#9CA3AF] mt-3 leading-relaxed">{post.intro}</p></summary><ol className="mt-5 space-y-3 border-t border-white/[0.07] pt-5">{post.steps.map((step,index)=><li key={step} className="flex gap-3 text-sm text-[#B5BBC9] leading-relaxed"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#7C4DFF]/15 text-[10px] text-[#B58BFF]">{index+1}</span>{step}</li>)}</ol><Link to="/register" className="text-sm text-[#B58BFF] hover:text-white inline-block mt-5">Appliquer dans mon journal →</Link></details>)}</div></PublicLayout>}

export function HelpPage(){return <PublicLayout title="Centre d'aide" subtitle="Trouve rapidement la bonne ressource."><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><HelpCard to="/faq" t="FAQ" d="Réponses aux questions courantes."/><HelpCard to="/platforms" t="Plateformes" d="Compatibilité et futures intégrations."/><HelpCard to="/contact" t="Support" d="Écris directement à l'équipe."/><HelpCard to="/blog" t="Guides" d="Bonnes pratiques pour progresser."/><HelpCard to="/security" t="Sécurité" d="Protection du compte et des données."/><HelpCard to="/app/settings" t="Mon compte" d="Profil, formule et préférences."/></div></PublicLayout>}
const HelpCard=({to,t,d})=><Link to={to} className="card-elev p-6 hover:border-[#7C4DFF]/40 transition"><h2 className="font-semibold">{t}</h2><p className="text-sm text-[#9CA3AF] mt-2">{d}</p><span className="text-[#B58BFF] text-sm inline-block mt-4">Ouvrir →</span></Link>;

export function AffiliatePage(){return <PublicLayout title="Programme partenaire en préparation" subtitle="Les candidatures ne créent actuellement aucun droit à commission."><div className="grid md:grid-cols-2 gap-5 max-w-4xl mx-auto"><div className="card-elev p-7"><h2 className="text-xl font-semibold">Une communication responsable</h2><p className="text-sm text-[#9CA3AF] mt-3">Le futur programme pourra s’adresser aux formateurs, créateurs et communautés qui parlent de processus et de discipline sans promettre de gains.</p><div className="space-y-2 mt-5 text-sm">{["Aucune promesse de rendement","Transparence sur les liens partenaires","Respect de l’identité PipsEvo","Conditions écrites avant activation"].map(x=><div key={x} className="flex gap-2"><Check className="w-4 h-4 text-[#00E676]"/>{x}</div>)}</div></div><div className="card-elev p-7"><h2 className="text-xl font-semibold">Manifester son intérêt</h2><p className="text-sm text-[#9CA3AF] mt-3">Présente ton audience et ton approche. L’équipe te recontactera uniquement lorsque le programme sera prêt.</p><Link to="/contact" className="btn-primary block text-center mt-6">Contacter l’équipe</Link><Link to="/affiliate-terms" className="text-xs text-[#B58BFF] block text-center mt-4">Lire les conditions préliminaires</Link></div></div></PublicLayout>}

function Footer(){return <footer className="border-t border-white/5 px-5 py-10"><div className="max-w-6xl mx-auto grid sm:grid-cols-3 gap-6 text-sm"><div><Logo/><p className="text-[#6B7280] mt-3">Journal et discipline pour traders financés.</p><p className="text-[10px] text-[#4B5563] mt-3">PipsEvo ne fournit aucun conseil financier ni signal.</p></div><div><div className="font-semibold mb-3">Aide</div><div className="flex flex-col gap-2 text-[#9CA3AF]"><Link to="/help">Centre d'aide</Link><Link to="/contact">Contact</Link><Link to="/platforms">Plateformes et imports</Link><Link to="/blog">Guides</Link><Link to="/faq">FAQ</Link><Link to="/affiliate">Programme partenaire</Link></div></div><div><div className="font-semibold mb-3">Légal</div><div className="flex flex-col items-start gap-2 text-[#9CA3AF]"><Link to="/terms">Conditions d'utilisation</Link><Link to="/privacy">Confidentialité</Link><Link to="/security">Sécurité</Link><Link to="/affiliate-terms">Conditions partenaires</Link><button onClick={openCookieSettings} className="hover:text-white">Gérer les cookies</button></div></div></div></footer>}
